### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by flfsbr** [hoganri/wex-bitcoin-litecoin-arbitrage#1]
Alway the script return me this message:

Trade not profitable.
111
Traceback (most recent call last):
  File "wexBitrage.py", line 126, in <module>
    except URLError, e:
NameError: name 'URLError' is not defined

**Comment by hoganri** [comment]
Are you using a valid API key/secret?

**Comment by flfsbr** [comment]
Sure.

**Comment by hoganri** [comment]
What version of Python are you running?
